/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Campaign {
  'id' : CampaignId,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'deadline' : bigint,
  'isActive' : boolean,
  'videoUrls' : Array<string>,
  'imageIds' : Array<string>,
  'targetAmount' : bigint,
  'category' : string,
  'currentAmount' : bigint,
}
export type CampaignId = string;
export interface CampaignInput {
  'title' : string,
  'description' : string,
  'deadline' : bigint,
  'videoUrls' : Array<string>,
  'imageIds' : Array<string>,
  'targetAmount' : bigint,
  'category' : string,
}
export interface CampaignStats {
  'totalRaised' : bigint,
  'supporterCount' : bigint,
}
export interface Donation {
  'id' : DonationId,
  'donorPhone' : string,
  'paymentMethod' : PaymentMethod,
  'createdAt' : bigint,
  'donorName' : string,
  'isAnonymous' : boolean,
  'campaignId' : CampaignId,
  'currency' : string,
  'amountUSD' : bigint,
  'donorEmail' : string,
  'amount' : bigint,
  'transactionId' : string,
}
export type DonationId = string;
export interface DonationInput {
  'donorPhone' : string,
  'paymentMethod' : PaymentMethod,
  'donorName' : string,
  'isAnonymous' : boolean,
  'campaignId' : CampaignId,
  'currency' : string,
  'amountUSD' : bigint,
  'donorEmail' : string,
  'amount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface ImageMetadata {
  'id' : string,
  'originalName' : string,
  'contentType' : string,
  'blob' : ExternalBlob,
  'size' : bigint,
  'uploadTime' : bigint,
}
export interface LegalPage {
  'id' : string,
  'content' : string,
  'updatedAt' : bigint,
}
export type PaymentMethod = {
    'stripe' : { 'status' : string, 'sessionId' : string }
  } |
  { 'bankTransfer' : { 'reference' : string } } |
  { 'crypto' : { 'walletAddress' : string, 'txHash' : string } };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearUpiQrCode' : ActorMethod<[], undefined>,
  'createCampaign' : ActorMethod<[CampaignInput], CampaignId>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteCampaign' : ActorMethod<[CampaignId], undefined>,
  'getActiveCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getAllCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getAllDonations' : ActorMethod<[], Array<Donation>>,
  'getAllImageMetadata' : ActorMethod<[], Array<ImageMetadata>>,
  'getAllLegalPages' : ActorMethod<[], Array<LegalPage>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaign' : ActorMethod<[CampaignId], [] | [Campaign]>,
  'getCampaignDonations' : ActorMethod<[CampaignId], Array<Donation>>,
  'getCampaignStats' : ActorMethod<[CampaignId], CampaignStats>,
  'getCampaignsSortedByAmountRaised' : ActorMethod<[], Array<Campaign>>,
  'getCampaignsSortedByCreationDate' : ActorMethod<[], Array<Campaign>>,
  'getCampaignsSortedByDeadline' : ActorMethod<[], Array<Campaign>>,
  'getDonationStats' : ActorMethod<[], [bigint, bigint, bigint]>,
  'getDonationsByCampaign' : ActorMethod<[CampaignId], Array<Donation>>,
  'getImageArrival' : ActorMethod<[], Uint8Array>,
  'getImageBlob' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getImageMetadata' : ActorMethod<[string], [] | [ImageMetadata]>,
  'getLegalPage' : ActorMethod<[string], [] | [LegalPage]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUpiQrCode' : ActorMethod<[], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLegalPage' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUpiQrCode' : ActorMethod<[string], undefined>,
  'submitDonation' : ActorMethod<[DonationInput], DonationId>,
  'toggleCampaignStatus' : ActorMethod<[CampaignId], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCampaign' : ActorMethod<[CampaignId, CampaignInput], undefined>,
  'uploadImage' : ActorMethod<
    [string, string, string, bigint, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];