/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CampaignInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Int,
  'videoUrls' : IDL.Vec(IDL.Text),
  'imageIds' : IDL.Vec(IDL.Text),
  'targetAmount' : IDL.Nat,
  'category' : IDL.Text,
});
export const CampaignId = IDL.Text;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Campaign = IDL.Record({
  'id' : CampaignId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'deadline' : IDL.Int,
  'isActive' : IDL.Bool,
  'videoUrls' : IDL.Vec(IDL.Text),
  'imageIds' : IDL.Vec(IDL.Text),
  'targetAmount' : IDL.Nat,
  'category' : IDL.Text,
  'currentAmount' : IDL.Nat,
});
export const DonationId = IDL.Text;
export const PaymentMethod = IDL.Variant({
  'stripe' : IDL.Record({ 'status' : IDL.Text, 'sessionId' : IDL.Text }),
  'bankTransfer' : IDL.Record({ 'reference' : IDL.Text }),
  'crypto' : IDL.Record({ 'walletAddress' : IDL.Text, 'txHash' : IDL.Text }),
});
export const Donation = IDL.Record({
  'id' : DonationId,
  'donorPhone' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'createdAt' : IDL.Int,
  'donorName' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'campaignId' : CampaignId,
  'currency' : IDL.Text,
  'amountUSD' : IDL.Nat,
  'donorEmail' : IDL.Text,
  'amount' : IDL.Nat,
  'transactionId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ImageMetadata = IDL.Record({
  'id' : IDL.Text,
  'originalName' : IDL.Text,
  'contentType' : IDL.Text,
  'blob' : ExternalBlob,
  'size' : IDL.Nat,
  'uploadTime' : IDL.Int,
});
export const LegalPage = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const CampaignStats = IDL.Record({
  'totalRaised' : IDL.Nat,
  'supporterCount' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const DonationInput = IDL.Record({
  'donorPhone' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'donorName' : IDL.Text,
  'isAnonymous' : IDL.Bool,
  'campaignId' : CampaignId,
  'currency' : IDL.Text,
  'amountUSD' : IDL.Nat,
  'donorEmail' : IDL.Text,
  'amount' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearUpiQrCode' : IDL.Func([], [], []),
  'createCampaign' : IDL.Func([CampaignInput], [CampaignId], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCampaign' : IDL.Func([CampaignId], [], []),
  'getActiveCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
  'getAllImageMetadata' : IDL.Func([], [IDL.Vec(ImageMetadata)], ['query']),
  'getAllLegalPages' : IDL.Func([], [IDL.Vec(LegalPage)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaign' : IDL.Func([CampaignId], [IDL.Opt(Campaign)], ['query']),
  'getCampaignDonations' : IDL.Func(
      [CampaignId],
      [IDL.Vec(Donation)],
      ['query'],
    ),
  'getCampaignStats' : IDL.Func([CampaignId], [CampaignStats], ['query']),
  'getCampaignsSortedByAmountRaised' : IDL.Func(
      [],
      [IDL.Vec(Campaign)],
      ['query'],
    ),
  'getCampaignsSortedByCreationDate' : IDL.Func(
      [],
      [IDL.Vec(Campaign)],
      ['query'],
    ),
  'getCampaignsSortedByDeadline' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getDonationStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'getDonationsByCampaign' : IDL.Func(
      [CampaignId],
      [IDL.Vec(Donation)],
      ['query'],
    ),
  'getImageArrival' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
  'getImageBlob' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getImageMetadata' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ImageMetadata)],
      ['query'],
    ),
  'getLegalPage' : IDL.Func([IDL.Text], [IDL.Opt(LegalPage)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUpiQrCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveLegalPage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUpiQrCode' : IDL.Func([IDL.Text], [], []),
  'submitDonation' : IDL.Func([DonationInput], [DonationId], []),
  'toggleCampaignStatus' : IDL.Func([CampaignId], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateCampaign' : IDL.Func([CampaignId, CampaignInput], [], []),
  'uploadImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CampaignInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Int,
    'videoUrls' : IDL.Vec(IDL.Text),
    'imageIds' : IDL.Vec(IDL.Text),
    'targetAmount' : IDL.Nat,
    'category' : IDL.Text,
  });
  const CampaignId = IDL.Text;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Campaign = IDL.Record({
    'id' : CampaignId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'deadline' : IDL.Int,
    'isActive' : IDL.Bool,
    'videoUrls' : IDL.Vec(IDL.Text),
    'imageIds' : IDL.Vec(IDL.Text),
    'targetAmount' : IDL.Nat,
    'category' : IDL.Text,
    'currentAmount' : IDL.Nat,
  });
  const DonationId = IDL.Text;
  const PaymentMethod = IDL.Variant({
    'stripe' : IDL.Record({ 'status' : IDL.Text, 'sessionId' : IDL.Text }),
    'bankTransfer' : IDL.Record({ 'reference' : IDL.Text }),
    'crypto' : IDL.Record({ 'walletAddress' : IDL.Text, 'txHash' : IDL.Text }),
  });
  const Donation = IDL.Record({
    'id' : DonationId,
    'donorPhone' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'createdAt' : IDL.Int,
    'donorName' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'campaignId' : CampaignId,
    'currency' : IDL.Text,
    'amountUSD' : IDL.Nat,
    'donorEmail' : IDL.Text,
    'amount' : IDL.Nat,
    'transactionId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ImageMetadata = IDL.Record({
    'id' : IDL.Text,
    'originalName' : IDL.Text,
    'contentType' : IDL.Text,
    'blob' : ExternalBlob,
    'size' : IDL.Nat,
    'uploadTime' : IDL.Int,
  });
  const LegalPage = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CampaignStats = IDL.Record({
    'totalRaised' : IDL.Nat,
    'supporterCount' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const DonationInput = IDL.Record({
    'donorPhone' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'donorName' : IDL.Text,
    'isAnonymous' : IDL.Bool,
    'campaignId' : CampaignId,
    'currency' : IDL.Text,
    'amountUSD' : IDL.Nat,
    'donorEmail' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearUpiQrCode' : IDL.Func([], [], []),
    'createCampaign' : IDL.Func([CampaignInput], [CampaignId], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCampaign' : IDL.Func([CampaignId], [], []),
    'getActiveCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllDonations' : IDL.Func([], [IDL.Vec(Donation)], ['query']),
    'getAllImageMetadata' : IDL.Func([], [IDL.Vec(ImageMetadata)], ['query']),
    'getAllLegalPages' : IDL.Func([], [IDL.Vec(LegalPage)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaign' : IDL.Func([CampaignId], [IDL.Opt(Campaign)], ['query']),
    'getCampaignDonations' : IDL.Func(
        [CampaignId],
        [IDL.Vec(Donation)],
        ['query'],
      ),
    'getCampaignStats' : IDL.Func([CampaignId], [CampaignStats], ['query']),
    'getCampaignsSortedByAmountRaised' : IDL.Func(
        [],
        [IDL.Vec(Campaign)],
        ['query'],
      ),
    'getCampaignsSortedByCreationDate' : IDL.Func(
        [],
        [IDL.Vec(Campaign)],
        ['query'],
      ),
    'getCampaignsSortedByDeadline' : IDL.Func(
        [],
        [IDL.Vec(Campaign)],
        ['query'],
      ),
    'getDonationStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
    'getDonationsByCampaign' : IDL.Func(
        [CampaignId],
        [IDL.Vec(Donation)],
        ['query'],
      ),
    'getImageArrival' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
    'getImageBlob' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getImageMetadata' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ImageMetadata)],
        ['query'],
      ),
    'getLegalPage' : IDL.Func([IDL.Text], [IDL.Opt(LegalPage)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUpiQrCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLegalPage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUpiQrCode' : IDL.Func([IDL.Text], [], []),
    'submitDonation' : IDL.Func([DonationInput], [DonationId], []),
    'toggleCampaignStatus' : IDL.Func([CampaignId], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateCampaign' : IDL.Func([CampaignId, CampaignInput], [], []),
    'uploadImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };